---
name: Build and deploy react app to cloudfront
on:
  push:
    branches: [ develop ]
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: react-static-content
      DIST: build
      REGION: us-west-2
      # DIST_ID: <ID>
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop
    - uses: actions/setup-node@v3
      with:
        node-version: 16.13.0
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}
    - name: Install Dependencies
      run: |
        node --version
        npm ci --production
    - name: Build Static Website
      run: npm run build

    - name: Copy files to the production website with the AWS S3 CLI
      run: |
        aws s3 sync --delete build/ s3://${{ ENV.BUCKET }}
